# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1e00781bdc9cdcf34ef50262e86fae47cea66b59d70823abf01d3e19fdf75e7c90891d917c09c78d916bd678327378804eadf4b49497fe1ca26e45fe22fced3

test:
  secret_key_base: cfda5dd9f6288506f044db9d58235c2abebb8c78e2cb7dd842944f565a026e4c17661b9ef5817e08cc1416326f6c348a6285b03afd3efc5ba79b0a4eb9d8e02e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
